### ISSUE TITLE
FID training script

### ISSUE THREAD

**Issue by conan1024hao** [microsoft/LayoutGeneration#37]
Hi, could you provide the training bash script for the FID training code in [here](https://github.com/microsoft/LayoutGeneration/tree/1498ff300710b4fc204aece537582d37ca447fc7/LayoutFormer%2B%2B/fid)? Thank you!

**Comment by kaoshizhou** [comment]
Hi @conan1024hao,

Due to the mismatch of the dataset directory structures between LayoutPrompter and LayoutFormer++, some code needs to be modified before training FID. The minimal change we recommend is to change the code [here](https://github.com/microsoft/LayoutGeneration/blob/main/LayoutFormer%2B%2B/src/data/base.py#L32-L33) to `self.pre_processed_dir = self.raw_dir`.

1. For RICO, the training script is 
```python
python train.py --data_dir /path/to/LayoutGeneration/LayoutPrompter/dataset --dataset rico --num_label 25 --max_num_elements 20
```
2. For PubLayNet, the training script is 
```python
python train.py --data_dir /path/to/LayoutGeneration/LayoutPrompter/dataset --dataset publaynet --num_label 5 --max_num_elements 20
```
Remember to switch the environment according to [readme](https://github.com/microsoft/LayoutGeneration/tree/main/LayoutFormer%2B%2B) to avoid the conflict of `utils` packages.

For your own dataset, you should set the correct `num_label` and `max_num_elements`.

BTW, the FID models are already available [here](https://github.com/microsoft/LayoutGeneration/tree/main/LayoutFormer%2B%2B/src/net). Hope they can help you well :)
